### PR TITLE
Filters For Variable Output

### PR DESCRIPTION
**Pull request by paularmstrong**
Added filters for variable output. Handy for transcoding raw data into something useful for display. This is definitely just a start, as they are relatively easy to implement. It'd be great to also look into a way to add custom filters.
## Usage

```
{{ foo|filter }}
{{ foo|filter('options') }}
```
### Example:

```
{{ myDate|date('F jS, Y') }} // August 6th, 2011
{{ foo|title }} // converts 'my title' to 'My Title'
{{ myArray|join(', ')|title }} // join array and then title case
```
## Currently Implemented
1. lower
2. upper
3. capitalize
4. title
5. join
6. length
7. url_encode
8. url_decode
9. json_encode
10. striptags
11. date
## Tests!

Also added [node unit](https://github.com/caolan/nodeunit) as a devDependency and wrote simple unit tests for all filters.

### CODE REVIEW

**Comment by paularmstrong** [comment]
Forgot to note: Also added pre-commit and post-merge hooks that will, once you've run `make` once, always auto-update themselves. The pre-commit hook strips trailing whitespace from all changed files and ensures JSLint and all tests pass before allowing any commits.

**Comment by skid** [comment]
Merged this one. Great job. 

P.S. It's good to do this when you're creating the compiled code.

``` javascript
    output = '__filters.' + matches[1] + '(' + variable + ', ' + matches[2] + ')';
```

instead of

``` javascript
    output = '__filters["' + matches[1] + '"](' + variable + ', ' + matches[2] + ')';
```

Since we already have the filters predefined in the module and dot-based property lookup is faster.
I'll get to that and escaping the filter arguments in a few days if you don't do it first :)

**Comment by paularmstrong** [comment]
Yeah, I went with brackets as the "safer" bet, but I guess that it's an arguable tradeoff: should there be an enforcement mechanism for (future) custom-filters to require being able to be used with dot notation? (I think yes)

**Comment by skid** [comment]
I think it's better  to make filter names only valid JS variable names and we can check while compiling.

**Pull request merged**
